### PR TITLE
Slight tweaks to Captain's Quarters on Pubbystation.

### PR DESCRIPTION
**Pull request by ActualRory**
Removes Medieval Armour. Adds flavourful items.

:cl: MrRory
tweak: The Captain of Pubbystation has thrown out his LARPing gear and brought aboard his old trunk.
/:cl:

Items:
>Spare telescopic baton to Captain's Locker.

>Ship in a bottle on the captain's personal desk within his sleeping area, to replace the fork that was there for seemingly no reason.

>Adds an old footlocker/trunk with the following contents:
                   -A book, randomly generated from the library database, to give the captain something to read. Different every round and pulls literally anything from the library database, so should lead to some hearty laughs on occasion when it turns out to be the Lusty Unathi Maid. Until the database gets hooked up serverside, it spawns this; https://i.gyazo.com/4b35dfc4e3300c03fcc2fc0e90db57ec.png
                    -Antique .45 Pistol with seven shots. This item isn't really seen in-game, so it fits here as a flavourful item the Captain picked up on his military campaigns and eventful career. To cut off any balance concerns, it has seven shots with no practical way to replace ammo, is locked up in the Captain's Bedroom which is harder to get to than the killing machine Antique Caplaser, and is pretty much one of the most secure items on the station, being harder to get than an all-access ID or roundstart nukedisk. Worst case; Captain uses it to perform one execution, then has to lock it away again because there's only a single bullet left, tops.
                    -A gift. Presumably from an old friend or lover, down to personal preference as to the story players weave for its existence. When opened provides a random inconsequential item, same story as the random book. Has potential to be meaningful or hilarious.
                    -Premium cigar case. The Captain didn't have one of these in his quarters, so I threw it in here as another thing he picked up on his travels.
                    -An old pipe for those too classic to the cigar case, I like to believe this belonged to a superior officer, good friend, or father-figure.
                    -A zippo lighter, to light the cigars and pipe. Might be worth making a unique Captain's Zippo lighter in future, with fancy engraving and flavour and such. That'd be very nice.
                    -Two bottles of Lizard Wine. Chosen because you never really see them anywhere and their description is as follows; "An alcoholic beverage from Space China, made by infusing lizard tails in ethanol. Inexplicably popular among command staff." Something the Cap would have acquired in his adventures through one means or another.

### CODE REVIEW

**Comment by ActualRory** [comment]
Think I might have clipped the Captain's Quarters camera. Lemme check.

**Comment by Kevak** [comment]
Looks probably fine. Ye used mapmerger?

**Comment by Partheo** [comment]
Please list these items, or include a picture. You can't just say "I added things."

Mapmerge was done just fine.

**Comment by ActualRory** [comment]
Clarified, pretty much as I showed you beforehand Partheo.
But aye, explained in detail now for the purposes of transparency and clarity.

**Comment by Kevak** [comment]
Looks good. We ready to merge?

**Comment by Partheo** [comment]
Happy with the changes as discussed with Rory- my only concern was the pistol, but after thinking about it, I think it's a good addition.

**Pull request merged**
