### PR TITLE
Re-adds greytide.

### PR DESCRIPTION
**Pull request by ActualRory**
See above. Can't have those assistants getting on a high horse with their wacky rainbow jumpsuits.
Also some minor string and config housekeeping.

:cl: MrRory
config: Some minor string and config changes.
tweak: To cut costs, all assistants are now issued secondhand grey jumpsuits.
/:cl:

### CODE REVIEW

**Comment by Partheo** [comment]
Using this to test labels. I want to see if the emoji are annoying and if we can ditch some.

**Comment by Kevak** [comment]
Code looks fine. Check through the megacarp names bit though. I know there are some spelling errors somewhere in the file from upstream.

**Comment by ActualRory** [comment]
Righto, will check upstream and run it all through a spell checker.

Open to suggestions for anything else worth squeezing in there.

**Comment by Kevak** [comment]
Maybe don't do MacOS for an AI name. Apple.. Does not like free advertisement for some reason. You'd think they would.

**Comment by Kevak** [comment]
We merge ready?

**Comment by ActualRory** [comment]
Yep, we ready.

**Pull request merged**
